icon_add = I(_class='fa fa-plus')
icon_cancel = I(_class = 'fa fa-times')
icon_usercircle = I(_class = 'fa fa-user')
icon_cal = I(_class = 'fa fa-calendar')
icon_clock = I(_class = 'fa fa-clock-o')
icon_question = I(_class = 'fa fa-question-circle-o')
icon_marker = I(_class = 'fa fa-map-marker')
icon_calendar = I(_class = 'fa fa-calendar')
icon_calendar_plus = I(_class = 'fa fa-calendar-plus-o')
icon_calendar_o = I(_class = 'fa fa-calendar-o')